### ISSUE TITLE
dependency uuid not found

### ISSUE THREAD

**Issue by chepe263** [Mimieam/phaser-mobile-template#1]
there's no bower.json or package.json on the repo.

Replace 

`<script src="lib/bower_components/node-uuid/uuid.js"></script>`

with 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/node-uuid/1.4.8/uuid.min.js"></script>`

**Comment by Mimieam** [comment]
Hey @chepe263 Thanks for point this out. It's been updated now :)
